---
application:
  name: "sig"
  project: "rgrghh"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "leaf"
  version: "11"
routers:
- name: "main-sig"
  routes:
  - application_name: "sig"
    paths:
    - "/*"
