---
application:
  name: "simple-example-node-with-postgresql"
  project: "rgrgff"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "leaf"
  version: "9"
routers:
- name: "main-simple-example-node-with-postgresql"
  routes:
  - application_name: "simple-example-node-with-postgresql"
    paths:
    - "/*"
